feat: add clamp function
TheLudd/yafu-mono pull request #1
Opened 2020-12-29 15:11 UTC by olchyk98

```
const clampBeginnerELO = clamp(200, 1950)
const taskValues = [50, 840, 3200]

taskValues.map(clampBeginnerELO) // [200, 840, 1950]
```

2020-12-29 15:28 UTC, TheLudd requested changes

2020-12-29 15:28 UTC, TheLudd commented on modules/yafu/lib/clamp.js
> +
:bomb:

2020-12-29 15:30 UTC, olchyk98 commented on modules/yafu/lib/clamp.js
> +
☠️🔫

2020-12-30 10:02 UTC, TheLudd approved these changes

2020-12-30 10:04 UTC, merged